project:
  name: quickstart-aws-industrial-machine-connectivity
  owner: quickstart@amazon.com
  package_lambda: false
  shorten_stack_name: true
  s3_regional_buckets: true
  parameters:
    QSS3BucketName: $[taskcat_autobucket] # will need to follow 'virtual deployment' instructions in user guide 
    QSS3KeyPrefix: quickstart-aws-industrial-machine-connectivity/ # will need to follow 'virtual deployment' instructions in user guide 
    QSS3BucketRegion: $[taskcat_current_region]
  s3_bucket: tcat-quickstart-awsmv450lzj

tests:
  ICLTestVirtualMain:
    template: templates/IMC-main.template.yaml
    parameters:
      DeploymentType: "Virtual"
      EC2KeyPairName: OVERRIDE
      EdgeDeviceID: tcatvirtual
      GreengrassInstanceType: t3.small
      IgnitionInstanceType: t3.large
      PublicSubnet1CIDR: 10.0.128.0/20
      SitewiseMonitorEmail: OVERRIDE
      UserPublicIP: OVERRIDE
      VPCCIDR: 10.0.0.0/16
      VPCTenancy: default
      UnifyUsername: test@test.com
      UnifyPassword: test
    regions:
      - eu-central-1
  
  # ICLTestPhysicalMain:
  #   template: templates/IMC-main.template.yaml
  #   parameters:
  #     ModelingVendorType: "Asset Model Converter"
  #     AMCDriver: "IgnitionCirrusLink"
  #     DeploymentType: "Physical"
  #     EC2KeyPairName: OVERRIDE
  #     EdgeDeviceID: Physical
  #     GreengrassInstanceType: t3.small
  #     IgnitionInstanceType: t3.large
  #     PublicSubnet1CIDR: 10.0.128.0/20
  #     SitewiseMonitorEmail: OVERRIDE
  #     UserPublicIP: OVERRIDE
  #     VPCCIDR: 10.0.0.0/16
  #     VPCTenancy: default
  #     UnifyUsername: test@test.com
  #     UnifyPassword: test
  #   regions:
  #     - eu-central-1

  # ICLTestVirtualWorkload:
  #   template: templates/IMC-workload.template.yaml
  #   parameters:
  #     ModelingVendorType: "Asset Model Converter"
  #     AMCDriver: "IgnitionCirrusLink"
  #     DeploymentType: "Virtual"
  #     EC2KeyPairName: OVERRIDE
  #     EdgeDeviceID: Virtual
  #     VpcId: OVERRIDE
  #     EC2Subnet: OVERRIDE
  #     AZ: OVERRIDE
  #     GreengrassInstanceType: t3.small
  #     IgnitionInstanceType: t3.large
  #     SitewiseMonitorEmail: OVERRIDE
  #     UserPublicIP: OVERRIDE
  #     UnifyUsername: test@test.com
  #     UnifyPassword: test
  #   regions:
  #     - eu-central-1

  # ICLTestPhysicalWorkload:
  #   template: templates/IMC-workload.template.yaml
  #   parameters:
  #     ModelingVendorType: "Asset Model Converter"
  #     AMCDriver: "IgnitionCirrusLink"
  #     DeploymentType: "Physical"
  #     EC2KeyPairName: OVERRIDE
  #     EdgeDeviceID: Physical
  #     VpcId: OVERRIDE
  #     EC2Subnet: OVERRIDE
  #     AZ: OVERRIDE
  #     GreengrassInstanceType: t3.small
  #     IgnitionInstanceType: t3.large
  #     SitewiseMonitorEmail: OVERRIDE
  #     UserPublicIP: OVERRIDE
  #     UnifyUsername: test@test.com
  #     UnifyPassword: test
  #   regions:
  #     - eu-central-1

  ##################################### Element Analytics #####################################
  
  # ElementUnify:
  #   parameters:
  #     ModelingVendorType: "Element Unify"
  #     AMCDriver: "Element Unify"
  #     DeploymentType: "Physical"
  #     EC2KeyPairName: OVERRIDE
  #     EdgeDeviceID: Virtual
  #     GreengrassInstanceType: t3.small
  #     IgnitionInstanceType: t3.large
  #     PublicSubnet1CIDR: 10.0.128.0/20
  #     SitewiseMonitorEmail: OVERRIDE
  #     UserPublicIP: OVERRIDE
  #     VPCCIDR: 10.0.0.0/16
  #     VPCTenancy: default
  #     UnifyUsername: test@test.com
  #     UnifyPassword: test
  #     UnifyHostname: https://app001-aws.elementanalytics.com/
  #     UnifyOrgId: 123456
  #   regions:
  #     - eu-central-1